import { defineArrayMember, defineField, defineType } from "sanity";

import {
  orderField,
  publishedAtField,
  seoField,
  slugField,
} from "../../fields";
import {
  limits,
  requiredString,
  requiredText,
} from "../../fields/validators";

const INTAKE_MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;

const MODE_OF_STUDY = [
  { title: "Full-time", value: "full-time" },
  { title: "Part-time", value: "part-time" },
  { title: "Online", value: "online" },
  { title: "Hybrid", value: "hybrid" },
] as const;

export const program = defineType({
  name: "program",
  title: "Program",
  type: "document",
  groups: [
    { name: "content", title: "Basic", default: true },
    { name: "relations", title: "Relationships" },
    { name: "academic", title: "Academic" },
    { name: "admissions", title: "Admissions" },
    { name: "financial", title: "Financial" },
    { name: "career", title: "Career" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: requiredString("Title is required", limits.heading),
    }),
    slugField("title"),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "featuredImage",
      title: "Featured image",
      type: "imageWithAlt",
      group: "content",
      validation: (rule) => rule.required().error("Featured image is required"),
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "imageWithAlt" })],
      validation: (rule) => rule.max(12),
    }),
    defineField({
      name: "shortDescription",
      title: "Short description",
      type: "text",
      rows: 3,
      group: "content",
      validation: requiredText("Short description is required", 400),
    }),
    defineField({
      name: "overview",
      title: "Full overview",
      type: "richText",
      group: "content",
      validation: (rule) => rule.required().error("Overview is required"),
    }),
    defineField({
      name: "highlights",
      title: "Highlights",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.max(10),
    }),
    defineField({
      name: "quickFacts",
      title: "Quick facts",
      type: "array",
      group: "content",
      of: [
        defineArrayMember({
          type: "object",
          name: "quickFact",
          fields: [
            defineField({
              name: "label",
              title: "Label",
              type: "string",
              validation: requiredString("Label is required", limits.shortLabel),
            }),
            defineField({
              name: "value",
              title: "Value",
              type: "string",
              validation: requiredString("Value is required", 120),
            }),
          ],
          preview: {
            select: { title: "label", subtitle: "value" },
          },
        }),
      ],
      validation: (rule) => rule.max(8),
    }),
    defineField({
      name: "university",
      title: "University",
      type: "reference",
      group: "relations",
      to: [{ type: "university" }],
      validation: (rule) =>
        rule.required().error("A program must belong to one university"),
      description: "Destination is derived from this university — do not duplicate it.",
    }),
    defineField({
      name: "courseCategory",
      title: "Course category",
      type: "reference",
      group: "relations",
      to: [{ type: "courseCategory" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "studyLevel",
      title: "Study level",
      type: "reference",
      group: "relations",
      to: [{ type: "studyLevel" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "faculty",
      title: "Faculty",
      type: "reference",
      group: "relations",
      to: [{ type: "faculty" }],
    }),
    defineField({
      name: "degreeType",
      title: "Degree type",
      type: "reference",
      group: "relations",
      to: [{ type: "degreeType" }],
    }),
    defineField({
      name: "duration",
      title: "Duration",
      type: "string",
      group: "academic",
      description: 'e.g. "2 years"',
      validation: requiredString("Duration is required", 80),
    }),
    defineField({
      name: "credits",
      title: "Credits",
      type: "string",
      group: "academic",
      validation: (rule) => rule.max(80),
    }),
    defineField({
      name: "modeOfStudy",
      title: "Mode of study",
      type: "string",
      group: "academic",
      options: { list: [...MODE_OF_STUDY], layout: "radio" },
      validation: requiredString("Mode of study is required"),
    }),
    defineField({
      name: "language",
      title: "Language",
      type: "string",
      group: "academic",
      validation: requiredString("Language is required", limits.shortLabel),
    }),
    defineField({
      name: "intakeMonths",
      title: "Intake months",
      type: "array",
      group: "academic",
      of: [defineArrayMember({ type: "string" })],
      options: {
        list: INTAKE_MONTHS.map((month) => ({ title: month, value: month })),
      },
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "entryRequirements",
      title: "Entry requirements",
      type: "richText",
      group: "admissions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "englishRequirements",
      title: "English requirements",
      type: "richText",
      group: "admissions",
    }),
    defineField({
      name: "requiredDocuments",
      title: "Required documents",
      type: "richText",
      group: "admissions",
    }),
    defineField({
      name: "applicationDeadline",
      title: "Application deadline",
      type: "string",
      group: "admissions",
      validation: (rule) => rule.max(120),
    }),
    defineField({
      name: "currency",
      title: "Currency",
      type: "string",
      group: "financial",
      description: 'e.g. "USD", "GBP", "AUD"',
      validation: requiredString("Currency is required", 8),
    }),
    defineField({
      name: "annualTuition",
      title: "Annual tuition fee",
      type: "number",
      group: "financial",
      validation: (rule) =>
        rule.required().min(0).error("Annual tuition is required"),
    }),
    defineField({
      name: "applicationFee",
      title: "Application fee",
      type: "number",
      group: "financial",
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: "scholarshipAvailable",
      title: "Scholarship available",
      type: "boolean",
      group: "financial",
      initialValue: false,
    }),
    defineField({
      name: "scholarshipDetails",
      title: "Scholarship details",
      type: "richText",
      group: "financial",
      hidden: ({ parent }) => !parent?.scholarshipAvailable,
    }),
    defineField({
      name: "careerOpportunities",
      title: "Career opportunities",
      type: "richText",
      group: "career",
    }),
    defineField({
      name: "industry",
      title: "Industry",
      type: "string",
      group: "career",
      validation: (rule) => rule.max(120),
    }),
    orderField(),
    publishedAtField(),
    seoField(),
  ],
  orderings: [
    {
      title: "Sort order",
      name: "orderAsc",
      by: [{ field: "order", direction: "asc" }],
    },
    {
      title: "Title A–Z",
      name: "titleAsc",
      by: [{ field: "title", direction: "asc" }],
    },
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "university.name",
      media: "featuredImage.asset",
    },
  },
});
